language: php

sudo: true
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

addons:
  postgresql: "9.3"

before_script:
  - composer update --dev

script:
  - phpunit --configuration phpunit.travis.xml
